### ISSUE TITLE
Archive extract - support *.zst

### ISSUE THREAD

**Issue by lostthing** [cfgnunes/nautilus-scripts#1]
Currently file-roller has not fully support zst archive, we can check if `zstd` installed first, then run `tar --use-compress-program=unzstd -xvf $INPUT_FILES &`

**Comment by cfgnunes** [comment]
Thanks for requesting!

I've added this feature on commit: 1b31e685926f7e51a00ed4d14dd4fdee951df2dd

Could you test it?

**Comment by lostthing** [comment]
Tested with zstd v1.4.4, tar v1.30 on Ubuntu 20.04, both zst and tar.zst archives extracted fine.
Thanks!

**Comment by cfgnunes** [comment]
Hi, @lostthing ! I've updated the scripts (again). Can you retest it? Thanks!
