### ISSUE TITLE
Install script not running if whiptail is not available

### ISSUE THREAD

**Issue by femto-code** [cfgnunes/nautilus-scripts#10]
Tested on Fedora 39. The bash script does not work (no output) when `whiptail` is not installed on the system.
Maybe consider adding a note or a check for the command.

Thanks for the great script collection!

**Comment by cfgnunes** [comment]
Hi @femto-code !

I appreciate your feedback. In the latest version, I've addressed your comments by removing whiptail from the installer. Now, you can seamlessly install the scripts on any Linux distribution.

Thank you for your input!
