### ISSUE TITLE
Installer copies itself into scripts directory

### ISSUE THREAD

**Issue by femto-code** [cfgnunes/nautilus-scripts#12]
Hi! The installer copies itself (`install.sh`) into the file manager's scripts directory. This leads to a separate entry in the right-click menu (that is not functional).

I would suggest excluding them from the files to be copied. My PR #11 already proposes some changes with a similar direction. It could be easily extended to take care of generally excluding the following files at root from being copied:

- `install.sh`
- `.gitignore`
- (`README.md`)

Thanks for your time!

**Comment by cfgnunes** [comment]
Hi, Fento! Thank you again for your contribution. I think that your suggestion is important.

By the way, I did some modifications to the main screen of the install.sh. If you could retest this installer, I will be gratefully.

Thanks for your time!
![Screenshot from 2024-02-24 20-32-03](https://github.com/cfgnunes/nautilus-scripts/assets/5264823/21632f03-2b65-4fd8-af16-062df111b275)

**Comment by femto-code** [comment]
@cfgnunes Sure, will do some further testing of your changes tonight!
