### ISSUE TITLE
Use diffpdf to compare PDF files

### ISSUE THREAD

**Issue by chronos000** [cfgnunes/nautilus-scripts#13]
Thank you for putting together this great script collection.

I see you use meld to compare files and directories. It would be great if we could use diffpdf when detecting that the selected files are PDFs (choosing exactly 2 files, and both are PDFs)

I'm attaching a quick script I put together a couple of years ago to achieve this. It's probably not the tidiest, and might fail on certain conditions, but it generally works, and it could be used for ideas to implement this correctly.
[compare.txt](https://github.com/cfgnunes/nautilus-scripts/files/14581002/compare.txt)

**Comment by cfgnunes** [comment]
Hi @chronos000 ! Thank you again for this other feature request!

I have implemented the script **Compare with DiffPDF**.
You can find this script in: **Document PDF -> PDF tools**.

Soon, I will combine this script with the script that makes the comparison with Meld.


---

Should you have any additional ideas for new scripts or any other modifications, please don't hesitate to let me know, so I can implement them. Thank you!
