### ISSUE TITLE
Add ability to sort results when calculating checksums

### ISSUE THREAD

**Issue by chronos000** [cfgnunes/nautilus-scripts#15]
At this time, the scripts to calculate checksums return a single string for each file through a zenity window with no columns. This prevents any possibility to sort results.

If zenity is called with the "--column" option, then the output of md5sum (or any other hash function), could be placed in the appropriate column, thus giving the possibility of sorting each field.

The following code produces the intended behavior, giving initial results sorted by checksum:
```
sed '/^$/d' <<< $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS | xargs -d '\n' md5sum | sort | sed 's/^\([^ ]*\) \(.*\)$/\1\x0\2/' | \
zenity --width=900 --height=300 --list --title "Hashes de archivos" --text "Archivos seleccionados" --column "MD5" --column "Archivo"
```

This is the resulting window after running the code above:
![image](https://github.com/cfgnunes/nautilus-scripts/assets/23492233/095e8636-c7f5-4f25-b6c8-575cad959033)

**Comment by cfgnunes** [comment]
Hi @chronos000 ! Thanks for the feature request!

I have implemented this feature now. It is in the 'main' branch. Could you test?
Thanks for your time!

![Screenshot from 2024-03-13 19-17-12](https://github.com/cfgnunes/nautilus-scripts/assets/5264823/9d946911-f814-4e4b-aab9-cb41b3914406)
