### ISSUE TITLE
Add 'Paste while reconstructing path' script?

### ISSUE THREAD

**Issue by ak-42** [cfgnunes/nautilus-scripts#17]
Hello. I have another suggested script that, I think, would be useful for you to consider implementing.

Nautilus has no graphical way, that I'm aware of, to generate multiple folders nested in a path. What I mean by that is if you were in `~` and you needed to create `./some/large/number/of/nesting/folders/potentially/a/very/large/number/of/folders` you would have to do this manually in multiple clicks, or you'd have to resort to `mkdir -p` if you wanted to do this in any sort of efficient manner.
(KDE's Dolphin can do something similar, but to my knowledge, Nautilus cannot)

A real, practical use case I face for this is moving files between Wine prefixes, where a receiving Wine prefix expects the file in a specific folder structure. If a file is in `~/.local/share/Steam/steamapps/compatdata/1111111/pfx/drive_c/users/steamuser/AppData/Roaming/tracking/userFiles/settings/profile/settings.xml` and I want to move it to the same location in another Wine prefix, such as `~/.local/share/Steam/steamapps/compatdata/222222/pfx/drive_c/` I have to reconstruct the `/users/steamuser/AppData/Roaming/tracking/userFiles/settings/profile/` by hand (or via `mkdir -p`), which is also error-prone in case of capitals and other complexity.

The solution to this would be a script that can paste while reconstructing the origin path. The logic would be thus:
1. User would copy source files as normal.
2. Upon invoking the script, the logic would look at the name of the folder where it is being pasted.  If the folder name is the same as one of the folders in the path of the copied content, it would create any path found after the matched folder name, and paste the file(s) in the same location as the original path.

So, to use the above example, if I copied `~/.local/share/Steam/steamapps/compatdata/1111111/pfx/drive_c/users/steamuser/AppData/Roaming/tracking/userFiles/settings/profile/settings.xml` and pasted it into `~/.local/share/Steam/steamapps/compatdata/222222/pfx/drive_c/`, the script would identify that `drive_c` is present in the source path, and would create `/users/steamuser/AppData/Roaming/tracking/userFiles/settings/profile/` (perhaps using `mkdir -p`?) and put `settings.xml` into it.

Please let me know if you need any clarification. I know this is not exactly an everyday operation, but I have personally found myself needing to resort to `mkdir -p` often enough that having a graphical way to do this would be helpful.
Thank you for all your efforts so far.

**Comment by cfgnunes** [comment]
Hi @ak-42 ! Thanks for the feature request!

I understood the idea of the script. In fact, this new script can be useful when you have similar folders structures along the disk.
I will think about the logic of the script. I think it is not difficult.

The problem is just finding a combination of shortcuts to trigger this new script. Because Nautilus does not show the script menu if no file or directory has been selected...

**Comment by cfgnunes** [comment]
Hi again! After a long time thinking, while I understand the convenience such a feature would offer, I'm afraid that implementing a solution as specific as the one you've described will not be useful for many other users... As you mentioned, this operation might not be an everyday task for most users, and it could potentially add complexity to the interface for those who don't require such a feature.

For these reasons, I think that the implementation of this script will not be good.

Thank you again for your contribution, and I hope you continue to find the scripts useful for your file management needs. If you have any further questions or concerns, don't hesitate to reach out.

Best regards,
