### ISSUE TITLE
Document how to install scripts for all users

### ISSUE THREAD

**Issue by pacho2** [cfgnunes/nautilus-scripts#2]
I am unable to find where should I place the scripts to be seen by all users of the system, I am not sure if maybe it is a nautilus limitation... or I am looking at the wrong PATHs :/

Thanks a lot

**Comment by pacho2** [comment]
It seems they limit it intentionally :S
https://gitlab.gnome.org/GNOME/nautilus/-/issues/2849

**Comment by cfgnunes** [comment]
Hi @pacho2!
A workaround is to put in the directory: "/etc/skel/.local/share/nautilus/scripts".

More information:
https://linuxg.net/the-unix-and-linux-skeleton-directory-etcskel/

**Comment by pacho2** [comment]
I didn't know, thanks a lot for the workaround!

**Comment by cfgnunes** [comment]
Hi, @pacho2 !

Good news! This feature (**option to install scripts for all users**) is now included in the installer of the latest release:
https://github.com/cfgnunes/nautilus-scripts/releases/tag/17.9

**Comment by pacho2** [comment]
Thanks a lot!
