### ISSUE TITLE
Add openSUSE support

### ISSUE THREAD

**Issue by ak-42** [cfgnunes/nautilus-scripts#20]
Hi. Could you please consider adding openSUSE support (at least Tumbleweed)?
I'm happy to help test if needed.

After getting used to your excellent tools on Fedora, I miss them dearly on openSUSE…

If not, could you list all the dependencies in the documentation, so I can install them manually and put the scripts in the right place?

Thank you for your efforts

**Comment by cfgnunes** [comment]
Hi, @ak-42 ! Sure!

I'm downloading now the image of openSUSE Tumbleweed to make some tests and adjusts. When I'm done, I'll let you know.

**Comment by cfgnunes** [comment]
I'm pleased to inform you that it's now been implemented!

Your willingness to help test is greatly appreciated. This will help me ensure everything works smoothly on openSUSE Tumbleweed.
Looking forward to hearing from you soon.

The implementation is in the main branch.

**Comment by ak-42** [comment]
@cfgnunes Thank you, that was incredibly fast. I appreciate it.

I installed it from the release package (since I saw it was fresh) and ran the installer on up-to-date Tumbleweed, and it all went well. I tested a few of the scripts, and it all went as expected, but if I notice any issues, I'll make sure to submit an issue.
