### ISSUE TITLE
how to backup the current installed version

### ISSUE THREAD

**Issue by sabamdarif** [cfgnunes/nautilus-scripts#24]
I installed an older version of your script, which works great for me, but I also want to install the latest version. If I back up the /home/arif/.local/share/nautilus/scripts folder, will it back up my currently installed version ?

**Comment by cfgnunes** [comment]
Hi, @sabamdarif! Yes! If you back up this folder, it will back up your currently installed version.

Best regards,

**Comment by cfgnunes** [comment]
Related to #8
