### ISSUE TITLE
[Request] Move all files from multiple subfolders into the parent folder

### ISSUE THREAD

**Issue by defencedog** [cfgnunes/nautilus-scripts#26]
User should be able to select multiple subfolder & then issue the command to move all files/folders (within subfolder) to parent directory .. in case of same file name default should be overwrite

Possible solution: https://askubuntu.com/a/146643

**Comment by cfgnunes** [comment]
Hi @defencedog !

I’ve developed an experimental script that you can find here:  [Flatten a Nested Directory](https://github.com/cfgnunes/nautilus-scripts/blob/main/Directories%20and%20files/Flatten%20a%20nested%20directory)

Could you test it and share your feedback?  

Key features:  
- The script ensures no files are overwritten if they have the same name, to prevent data loss.  
- It also generates an `undo-flatten.sh` script, allowing you to easily revert the flattening process.  

Looking forward to hearing your thoughts!
