### ISSUE TITLE
Install script overly broad when removing existing scripts

### ISSUE THREAD

**Issue by sivolc73** [cfgnunes/nautilus-scripts#27]
I find it a bit odd that the install script will remove all scripts from the script folder.

Even with a preserve previous script I don't get why the install would remove folder or scripts unrelated to this project, maybe a little bit of logic would allow to remove only the scripts and folders known to the project? 

Other than that it's a really nice collection of scripts!

Thanks

**Comment by cfgnunes** [comment]
Thank you for your feedback!

The installer does include an option to preserve previous scripts by moving them to a separate directory. This way, you can ensure that no unrelated or custom scripts are lost during the process. The logic focuses on removing only the scripts known to the project, but we understand the concern and will consider improvements to make it even more selective.

Glad to hear you’re enjoying the collection of scripts!
Feel free to share any other suggestions.
Thanks again!

**Comment by cfgnunes** [comment]
Related to #8
