### ISSUE TITLE
Are these functions useful to add to `common-functions.sh`?

### ISSUE THREAD

**Issue by KlfJoat** [cfgnunes/nautilus-scripts#30]
I have long had a personal Nautilus script that allows me to right-click on a directory and pull out all of the media files to the parent directory. It is sort of like #26, except I only want certain subdirectory files to be pulled out.

Since I started using this project, I have tried to rewrite all of my Nautilus scripts to use the features and functions of this project. Functions like `_validate_file_mime_parallel` and `_run_task_parallel` have been very helpful in rebuilding it and even speeding things up.

However, I ran into two trouble spots that I couldn't figure out how to solve with the built-in functions, so I made my own. And the ultimate question is, are these functions useful enough for me to contribute to the project, or not?

**Function 1 - `_validate_file_ext_parallel`**

Some file types I'm interested in don't have good MIME type reporting from `file`. For example, they will only show `text/plain`, `application/octet-stream`, or `application/zip`. These include...
* `cbz`
* `cbr`
* `srt`
* `xspf`

So I copied the `_validate_file_mime_parallel` function and sub-function `_validate_file_mime`, and changed them to work with file extensions. The key difference being...

```bash
    if [[ -n "${par_select_ext}" ]]; then
        local file_ext=""
        file_ext=$(_get_filename_extension "${input_file}")
        grep --quiet --ignore-case --perl-regexp "(${par_select_ext})" <<<"${file_ext}" || return
    fi
```

Question 1:  Would you appreciate the contribution of those functions to `common-functions.sh`?

**Function 2 - `_get_files_in_dirs`**

Because the only thing being pulled into `$NAUTILUS_SCRIPT_SELECTED_URIS` is the directory name(s) I right-clicked on, I needed a way to get the names of files in that directory. I found no function to do that, so I created my own.

```bash
_get_files_in_dirs() {
    local input_dirs=$1
    local output_files=""
    for input_dir in ${input_dirs}; do
        output_files+=$( find "${input_dir}" -mindepth 1 -maxdepth 1 -printf "%p${FIELD_SEPARATOR}" )
    done
    printf "%s" "${output_files}"
}
```

Question 2:  Would you appreciate the contribution of this function to `common-functions.sh`? If so, I would need to expand my function to be a bit more general (e.g., add a parameter for depth, that kind of thing). 

Question 3:  If "yes" to the first two questions, would you like me to submit my script to pull media files out? I would also be willing to create a script for the more general case in #26.

**Comment by cfgnunes** [comment]
Thank you for sharing your experience and feedback! It’s wonderful to hear how you’ve integrated the project’s features into your workflow. It’s always exciting to see the project being used creatively and effectively.

As for your custom functions, I would absolutely love to see them! Whether or not they get directly incorporated, sharing them could provide valuable insights and inspiration for further development. Feel free to submit them or start a discussion about them—your contributions are greatly appreciated. 

Let me first explain the `_get_files` function's logic before answering your questions. The function processes and validates the input file list through stages:

1. **Stage 1: `_validate_file_preselect`**  
   This stage allows for validation of file attributes such as extensions, file type (e.g., file or directory), and can also expand directories to include their contents.

2. **Stage 2: `_validate_file_mime_parallel`**  
   Here, files are filtered based on their MIME types. This function can be used to include or exclude files depending on their MIME type.

3. **Stage 3: `_validate_conflict_filenames`**  
   In this final stage, the function checks for conflicts where multiple selected files share the same base name (e.g., `test.jpg` and `test.png`).

Now, regarding your functions:  

---

**Function 1 - `_validate_file_ext_parallel`**  
This function appears to overlap with the validation capabilities already provided by `_validate_file_preselect`. The `_validate_file_preselect` function allows filtering filenames using a list of extensions, which seems to achieve the same goal.  

> **Question 1: Would you appreciate the contribution of these functions to `common-functions.sh`?**  

I’d be interested in seeing a practical example where this function is necessary. Could you provide an example use case? If I understood correctly, it seems possible to achieve the same functionality by leveraging the existing parameters in `_validate_file_preselect`, making the implementation of `_validate_file_ext_parallel` redundant.  


---

**Function 2 - `_get_files_in_dirs`**

> Because the only thing being pulled into $NAUTILUS_SCRIPT_SELECTED_URIS is the directory name(s) I right-clicked on, I needed a way to get the names of files in that directory. I found no function to do that, so I created my own.

It is possible to use the function `_get_files` with the parameter `par_recursive=true`. In this way, it is possible to get the names of files in that directory.

See some script examples that use this parameter:

- `List largest files`
- `List all hashes`

> Question 2: Would you appreciate the contribution of this function to common-functions.sh? If so, I would need to expand my function to be a bit more general (e.g., add a parameter for depth, that kind of thing).

Before addressing your question, could you provide a practical example where this function would be necessary? Understanding a real use case would help clarify its utility and how it might complement or improve upon the existing functionality.

That said, I truly appreciate your willingness to contribute and your thoughtfulness in considering how to make the function more general, such as by adding parameters for depth. These enhancements could make it more versatile and valuable to the project.

> Question 3: If "yes" to the first two questions, would you like me to submit my script to pull media files out? I would also be willing to create a script for the more general case in #26.

I would really love to see your scripts. They could be incredibly helpful in generating new ideas and expanding the possibilities of the project. If you could share them via a fork, it would be much easier to review the new functionalities and better understand their potential applications.

Regarding case #26, I don’t think it would be difficult to implement using the functions already available. The reason for the delay in my response is that I’m still considering whether this functionality could be useful to a broader audience and address common, frequent use cases. This approach is intended to avoid creating scripts that might be too specific and have limited applicability.

---

Thank you again for your thoughtful feedback and willingness to contribute. I’m looking forward to reviewing your scripts and exploring how they can enrich the project!

**Comment by KlfJoat** [comment]
Hi

You're right. It looks like `_validate_file_preselect` seems to work in place of both of my functions. With one difference.

As written, the function either finds files with the provided extension(s) infinitely deep (`par_recursive=true`) or only in `input_files`.

My preference for this use case is to set `-maxdepth 1`. If I could pass in `-maxdepth` as a parameter, that would be great. 

As a test, I replaced the `if` statement at https://github.com/cfgnunes/nautilus-scripts/blob/5fa968a7a63d96157b79ed9768825b6dbda866ae/common-functions.sh#L2030 with the following. It should work as normal AND allow for `-maxdepth` to be configurable. Right now it is limited to 1 digit, but I'll expand the `case` statement if desired.

```bash
    case $par_recursive in
        [[:digit:]]) find_command+=" -maxdepth $par_recursive" ;;
        true) ;;
        *) find_command+=" -maxdepth 0" ;;
    esac
```

I ran my scripts with this change as well as a few of the other scripts you have, and it worked okay. 

By the way, is there some reason you don't use `-printf "%p${FIELD_SEPARATOR}"` in the `_validate_file_preselect` `find` command? It would save the later fork to `tr`.
https://github.com/cfgnunes/nautilus-scripts/blob/5fa968a7a63d96157b79ed9768825b6dbda866ae/common-functions.sh#L2052

**Comment by cfgnunes** [comment]
Hi @KlfJoat !

Thanks for sharing this modification. I've done a commit in: https://github.com/cfgnunes/nautilus-scripts/commit/ca31c3fcca3e5b2e4ea77fa497fce119ee5c7b48 that add this modification. Could you test if its ok? Now the `-maxdepth` is configurable.

---

> By the way, is there some reason you don't use `-printf "%p${FIELD_SEPARATOR}"` in the `_validate_file_preselect` `find` command? It would save the later fork to `tr`.

https://github.com/cfgnunes/nautilus-scripts/blob/5fa968a7a63d96157b79ed9768825b6dbda866ae/common-functions.sh#L2052


In this line, I tried using `-printf "%p${FIELD_SEPARATOR}"`, but I encountered issues in some cases. For some reason, the `$FIELD_SEPARATOR` (set to `\r`) didn’t work as expected inside the `find` command with `-printf`. If you’re able to identify the problem and help resolve it, that would be awesome! I suspect the issue might be related to the `\r` symbol, but I’m not entirely sure.

**Comment by KlfJoat** [comment]
Thanks, your update works just fine.

You said you were interested in the script I created. Here are the operative parts. My first version, before integrating with this project, was a script with a bunch of simple `mv *.ext ..` lines in it. Not even looping over a list of extensions or multiple extensions on one line; multiple `mv` commands on separate lines. (despite me having used `for` loops for 25+ years 😂)

```bash
_main() {
    local input_files=""
    local input_dirs=""
    local output_dir=""

    _display_wait_box "2"

    # The name of the dir to move files FROM
    input_dirs=$(_get_files "par_type=directory; par_recursive=false")

    # All of the files in $inputdirs
    input_files=$( _validate_file_preselect "${input_dirs}" "file" "" "" "1" )

    ### Craft $input_files from MIME types and extensions
    # Create $input_files from MIME types
    input_files=$(_validate_file_mime_parallel "${input_files}" "video/|audio/|image/|application/x-ms-reader|application/epub|application/vnd.rn-realmedia|text/vtt|application/x-mobipocket-ebook|application/vnd.ms-htmlhelp|application/pdf|application/x-shockwave-flash|text/rtf|application/vnd.oasis.opendocument|application/vnd.ms-office")

    # $FIELD_SEPARATOR ('\r') seems to get stripped from the final item in the variable. Add it back when there is something in there and the last char is not '\r'.
    if [[ -n ${input_files} ]] && [[ ${input_files:-1:1} != $(printf %s "$FIELD_SEPARATOR") ]]; then input_files+=$(printf %s "$FIELD_SEPARATOR"); fi


    # Add to $input_files from file extensions
    # Do this because sometimes, the mime type isn't exact enough.
    # For example, 'cbz' files only show as 'application/zip' or 'ssa' subtitles show as 'application/x-wine-extension-ini'???
    #
    # Extensions and what they're for...
# <snipped>
    #
    # TODO: Validate case insensitivity

    input_files+=$(_validate_file_preselect "${input_dirs}" "file" "" "cbz|cbr|pdb|azw3|f4v|mp4v|viv|srt|ass|ssa|idx|sub|smi|dfxp|lrc|xspf|afpk" "1")

    # In case I added too many '\r's above to the end of the file list
    input_files=$(_str_remove_empty_tokens "${input_files}")

    # The name of the dir to move files TO
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    ### Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "${input_files}" "${output_dir}"
    _close_wait_box

}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    output_file=$( _get_output_filename "${input_file}" "${output_dir}" "par_extension_opt=preserve" )

    std_output=$(_move_file "rename" "${input_file}" "${output_file}" 2>&1)
    _check_output "$?" "${std_output}" "${input_file}" "${output_file}" || return 1
}
```

Also, if you're serious about wanting feedback and contributions, I've got some other questions, comments, and ideas. I'll open other Issues for those.

**Comment by cfgnunes** [comment]
Hi @KlfJoat !

Your script is very good. However, I believe your function `_main` can be simplified. Instead of calling the functions `_validate_file_preselect` and `_validate_file_mime_parallel`, it would be possible to pass all the parameters at once to the `_get_files` function, since this function already calls these two internally.

For example:

```bash
input_dirs=$(_get_files "par_type=file;
                         par_recursive=1;
                         par_select_mime='video/|audio/|image/|application/x-ms-reader';
                         par_select_extension='cbz|cbr|pdb|azw3|f4v|mp4v|viv|srt|ass"
)
```

In this case, the parameters `par_select_mime` and `par_select_extension` acts as an AND operation. To make them work as an OR operation, we would need to modify the `_get_files` function.

It is interesting to avoid calling the functions `_validate_file_preselect` and `_validate_file_mime_parallel` externally, as they are resource-intensive and can significantly delay the task processing.

---

Finally, I'm interested in hearing your questions and comments. I'd also love to hear your ideas. Feel free to open the other issues, and I'll be happy to engage with them! 🙌

**Comment by KlfJoat** [comment]
> To make them work as an OR operation, we would need to modify the `_get_files` function.

I just took a look at it, and it does not look like an easy modification.

`_validate_file_preselect` is the thing that returns all files inside a directory. While it does that, it also filters by extension.

Looks like I would need to find all files, then run the names through a separate extension filter, and then through the MIME filter.

I'll take a closer look later tonight or tomorrow.

**Comment by cfgnunes** [comment]
About issue #26:

I’ve developed an experimental script that you can find here:  [Flatten a Nested Directory](https://github.com/cfgnunes/nautilus-scripts/blob/main/Directories%20and%20files/Flatten%20a%20nested%20directory)

Could you test it and share your feedback?  

Key features:  
- The script ensures no files are overwritten if they have the same name, to prevent data loss.
- It also generates an `undo-flatten.sh` script, allowing you to easily revert the flattening process.
