### ISSUE TITLE
Remove brackets - feature request 

### ISSUE THREAD

**Issue by frayja2002** [cfgnunes/nautilus-scripts#31]
I would like a script to remove the bracketed information in a filename.

I tried to modify one of the existing scripts with 
rename 's/\s*\([^\)]+\)//g' "$filename"
but keep getting an error log.

The ultimate goal is to turn (for example )...
DD WRT Router Configuration Part 1 (720p_30fps_H264-128kbit_AAC).mp4
into
DD WRT Router Configuration Part 1.mp4

All help appreciated.

**Comment by cfgnunes** [comment]
Hello @frayja2002 ! Thank you for using the scripts and for your detailed explanation of what you needed. I’ve implemented a script that removes the bracketed information in filenames, as you described. Could you test it in the new version and let me know if it works as expected? Your feedback would be greatly appreciated! 😊


Check the script:
https://github.com/cfgnunes/nautilus-scripts/blob/main/Rename%20files/Remove%20brackets

**Comment by frayja2002** [comment]
I have tested this on various files on my HDD & seems to work exactly as expected.

Your quick response & assistance with this is much appreciated.

Thaks
Alex
