### ISSUE TITLE
skip script if dependecy in not installable

### ISSUE THREAD

**Issue by Belingheri** [cfgnunes/nautilus-scripts#32]
During the installation process `./install.sh` i recived this error:
```
Problem: problem with installed package
  - installed package ffmpeg-7.0.2-4.fc41.x86_64 conflicts with ffmpeg-free provided by ffmpeg-free-7.0.2-7.fc41.x86_64 from fedora
  - package ffmpeg-7.0.2-4.fc41.x86_64 from rpmfusion-free conflicts with ffmpeg-free provided by ffmpeg-free-7.0.2-7.fc41.x86_64 from fedora
  - conflicting requests
```

I am not sure if uninstall the packages with conficts is a good idea so:
In you opinion is it possible that if there is some issue during the dependencies installation the script will install only the one that the installation part was ended good ?

Thanks

**Comment by cfgnunes** [comment]
Hi @Belingheri ,

Thank you for identifying this issue! I'll check the currently installed packages on Fedora to better understand the problem. Additionally, I'll implement a logic to handle this kind of conflict in the script soon. Once I finish, I'll update this issue with the details.

Thanks again for reporting this!

**Comment by cfgnunes** [comment]
Fix merged.
