### ISSUE TITLE
Scan with clamscan

### ISSUE THREAD

**Issue by Belingheri** [cfgnunes/nautilus-scripts#33]
I personally use this script in the context menu to scann file and move it in quarantine if infected.
If you want to add it:
``` sh
#!/bin/bash
# Script to scan files or folders with clamscan, with user-specific quarantine and intrusive notifications

QUARANTINE_DIR="$HOME/quarantine"  # User-specific quarantine directory

# Create the quarantine directory if it doesn't exist
if [ ! -d "$QUARANTINE_DIR" ]; then
    mkdir -p "$QUARANTINE_DIR"
    chmod 700 "$QUARANTINE_DIR"  # Protects access to the quarantine folder
fi

for ITEM in "$@"; do
    ORIGINAL_NAME=$(basename "$ITEM")
    DIRECTORY=$(dirname "$ITEM")
    TEMP_NAME=""

    # Check if it's a file or folder and rename accordingly
    if [ -f "$ITEM" ]; then
        TEMP_NAME=".$ORIGINAL_NAME.in-progress"
    elif [ -d "$ITEM" ]; then
        TEMP_NAME="$ORIGINAL_NAME-in-progress"
    else
        zenity --error --title="Error" --text="'$ITEM' is not a valid file or folder." --width=300
        continue
    fi

    # Rename the item
    mv "$ITEM" "$DIRECTORY/$TEMP_NAME"
    RENAMED_ITEM="$DIRECTORY/$TEMP_NAME"

    # Run the scan with clamscan
    SCAN_RESULT=$(clamscan -r "$RENAMED_ITEM")

    # Analyze the scan result
    if echo "$SCAN_RESULT" | grep -q "Infected files: 0"; then
        # Safe file
        zenity --info --title="ClamAV Scan" --text="The file or folder '$ORIGINAL_NAME' is safe." --width=300
        # Restore the original name
        mv "$RENAMED_ITEM" "$ITEM"
    else
        # Infected file: Move to quarantine
        zenity --warning --title="WARNING: Infected File" --text="'$ORIGINAL_NAME' is infected and will be moved to quarantine!" --width=300
        QUARANTINE_PATH="$QUARANTINE_DIR/$ORIGINAL_NAME"
        mv "$RENAMED_ITEM" "$QUARANTINE_PATH"
        zenity --error --title="File Moved to Quarantine" --text="The infected file has been moved to quarantine: '$QUARANTINE_PATH'" --width=300
    fi
done

```

ps. i am not so good with sh but **it work** so.

The script : 

1. rename the folder / file this "in-progress" suffix
2. run `clamscan`
3. remove the suffix
4. if ok send **invasive** notification with `zenity` 
5. if KO send **invasive** notification with `zenity` and move it into a quarantine folder

Tested on `Fedora Linux 41 (Workstation Edition)` with `Nautilus`
Dependences:

- `clamscan`
- `zenity` _on my os already installed (not by me)_

> [!WARNING]  
> You shoud install `freshclam` for update Virus Database with [little configuration](https://docs.clamav.net/manual/Usage/SignatureManagement.html)

> [!TIP]
> you can download and infected file from [eicar.org](https://www.eicar.org/download-anti-malware-testfile) to test the result

**Comment by cfgnunes** [comment]
Hi @Belingheri !

Thank you for the great suggestion! I've implemented the script, and you can check it out here:
[Scan for Malware (ClamAV)](https://github.com/cfgnunes/nautilus-scripts/blob/main/Security%20and%20recovery/Scan%20for%20malware%20(ClamAV))

At the moment, it performs basic operations: the script uses ClamAV (clamscan) to detect malware and lists any found threats. The user can then click on a detected file to view it in the folder, allowing them to either remove it or move it manually to another directory.

Could you please test the script and let me know your thoughts?

Thanks again for your idea!

**Comment by Belingheri** [comment]
Tested on `Fedora Linux 41 (Workstation Edition)` with `Nautilus`.
It worked perfect!

The only note that i can do is that if the user do not install [FreshClam](https://docs.clamav.net/manual/Usage/SignatureManagement.html#freshclam) and create the service to update the signature database we can introduce a false state of security  because clamav use old signatures.

Maybe the in the installation process it can be done!  

Thanks a lot for your work!

Some screen:

![Screenshot From 2024-12-11 20-20-42](https://github.com/user-attachments/assets/da823731-e853-41b9-99c8-8764553fff99)
![Screenshot From 2024-12-11 20-22-03](https://github.com/user-attachments/assets/37b7f351-276d-4a2a-b5b9-bde571fccab6)
