### ISSUE TITLE
Overwrites scripts already in directory

### ISSUE THREAD

**Issue by johnschriner** [cfgnunes/nautilus-scripts#8]
The scripts are great, thank you.
The only issue is that it has it emptied and overwrote the scripts already in the directory?
Worth looking into.  Thanks!

**Comment by vlahovivan** [comment]
I've notices the same thing and created a pull request #9 to fix that.

**Comment by cfgnunes** [comment]
Hi @johnschriner! Thanks for the suggestion. @vlahovivan solved this issue.
Thanks for the pull request, @vlahovivan!

**Comment by cfgnunes** [comment]
Now, I have added the question in the installer for the user: _Would you like to preserve the previous scripts? [y/N]_

Thanks for the contribution @johnschriner and @vlahovivan!

**Comment by cfgnunes** [comment]
Hi,  @johnschriner and @vlahovivan  !

Good news! I’ve refined the logic and simplified the installer. It now adds only the scripts from this project, without modifying any other files that may already exist in your Nautilus scripts folder (as suggested in #27).

This change is included in the latest release:
https://github.com/cfgnunes/nautilus-scripts/releases/tag/17.9.2

Could you give the new installer a try and let me know how it works for you?
